version: '3'

networks:
  dev:
    driver: bridge

volumes:
  dp_keys:

services:
  web:
    container_name:
      web
    depends_on:
      - gateway
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:80
    networks:
      - dev
    restart:
      on-failure

  gateway:
    container_name:
      gateway
    depends_on: 
      - chatservice
      - user_data_service
    build:
      context: ../AuthenticationGateway/AuthenticationGateway/AuthenticationGateway
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://*:80;"
    ports:
      - 8000:80
    networks:
      - dev
    volumes:
      - dp_keys:/root/.aspnet/DataProtection-Keys
    restart: 
      on-failure
    
  user_data_service:
    container_name:
      user_data_service
    build:
      context: ../UserDataService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://*:80;"
    #ports:
      #- 5001:80
    networks:
      - dev
    restart:
      on-failure

  chatservice:
    container_name: 
      chatservice
    build:
      context: ../ChatService
      dockerfile: Dockerfile
    ports:
      - 8124:8124
    depends_on:
      - chatservice-db
    networks:
      - dev

  chatservice-db:
    image: postgres
    container_name: chatservice-db
    environment:
      POSTGRES_PASSWORD: Password1!
      POSTGRES_USER: dev
    ports:
      - 5432:5432
    volumes:
      - ../ChatService/postgres:/docker-entrypoint-initdb.d
    networks:
      - dev

