version: '3'
services:
  Frontend:
    image: nginx:1.25.3
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - szachmatyNet-frontend
    volumes:
      - ${FRONTEND_PATH}:/usr/share/nginx/html
      - ./configs/frontendNginx/nginx-conf.conf:/etc/nginx/nginx.conf:ro
  FakeAuthenticationGateway:
    image: nginx:1.25.3
    container_name: authenticationGateway
    networks:
      - szachmatyNet-frontend
      - szachmatyNet-backend
    volumes:
      - ./configs/fakeAuthGateway/nginx-conf.conf:/etc/nginx/nginx.conf:ro
  ChatService:
    image: nginx:1.25.3
    container_name: chatService
    networks:
      - szachmatyNet-backend
  UserDataService:
    image: nginx:1.25.3
    container_name: userDataService
    networks:
      - szachmatyNet-backend
  AIService:
    image: nginx:1.25.3
    container_name: aiService
    networks:
      - szachmatyNet-backend
  GameLogicService:
    image: nginx:1.25.3
    container_name: gameLogicService
    networks:
      - szachmatyNet-backend
networks:
  szachmatyNet-frontend:
  szachmatyNet-backend: